SELECT
    e.ID,
    e.EVENT_ID,
    e.EVENT_TYPE_ID,
    e.DETECTION_TAG_ID,
    e.DRIVER_ID,
    e.MACHINE_ID,
    e.MACHINE_ACTIVATION_ID,
    e.ORGANISATION_ID,
    e.INTENSITY,
    e.LOCATION_READABLE        AS LOCATION,
    e.LATITUDE,
    e.LONGITUDE,
    e.EVENT_START_TIME         AS EVENT_DATETIME,
    e.EVENT_LOCAL_START_TIME   AS EVENT_LOCAL_DATETIME,
    e.EVENT_START_DATE         AS EVENT_DATE,
    e.EVENT_LOCAL_START_DATE   AS EVENT_LOCAL_DATE,
    e.CREATED_AT_BACKEND       AS CREATED_DATETIME,
    e.UPDATED_AT_BACKEND       AS UPDATED_DATETIME,
    e.EVENT_SOURCE,
    e.VIDEO_DURATION,
    e.SF_LOAD_DATE             AS LOAD_DATETIME
FROM "${source_db}".core_extensions.media_service_events e

 