SELECT UUID_STRING(l.ORGANISATION_ID, NVL(l.MACHINE_ID,'-1') || l.CENTRAL_ID) as ID, 
l.ORGANISATION_ID, 
MACHINE_ID, 
NUMBER as ISSUE_NUMBER, 
ISSUE_DATETIME, 
ISSUE_LOCAL_DATETIME, 
CONTINUATION, 
START_DISTANCE, 
END_DISTANCE, 
UNITS, 
VEHICLE_WEIGHT, 
TYPE_NAME as LICENCE_TYPE, 
STATUS, 
STATUS_LAST_MODIFIED_DATETIME, 
STATUS_LAST_MODIFIED_LOCAL_DATETIME, 
DOLLAR_VALUE, 
CREDIT, 
AMOUNT, 
REGISTRATION_PLATE, 
FEE_AMOUNT, 
FEE_AMOUNT_GST, 
RUC_VEHICLE_TYPE, 
VEHICLE_COMBINATION, 
RUC_WEIGHT_FLAG, 
LOAD_DATETIME 
FROM "${source_db}".core_extensions.vehicle_licence l 
INNER JOIN "${access_db}"."${access_schema}"."${access_table}" aoa 
  ON l.ORGANISATION_ID = aoa.ORGANISATION_ID
 AND LOWER(aoa.REGION) = LOWER('${region}')
 AND UPPER(aoa.CLOUD)  = UPPER('${cloud}')
WHERE l.ORGANISATION_ID IS NOT NULL QUALIFY ROW_NUMBER() OVER (PARTITION BY l.CENTRAL_ID, l.ORGANISATION_ID, l.MACHINE_ID ORDER BY l.LOAD_DATETIME DESC) = 1;
