SELECT 
ID, 
gv.ORGANISATION_ID, 
GEOFENCE_ID, 
GEOFENCE_COMMON_ID as GEOFENCE_MAIN_ID, 
MACHINE_ID, 
ENTRY_TIMESTAMP as ENTRY_DATETIME, 
ENTRY_LOCAL_DATETIME, 
ENTRY_LOCAL_DATE, 
EXIT_TIMESTAMP as EXIT_DATETIME, 
EXIT_LOCAL_DATETIME, 
EXIT_LOCAL_DATE, 
ENTRY_ODOMETER, 
EXIT_ODOMETER, 
SF_LOAD_DATE as LOAD_DATETIME 
FROM "${source_db}".core_extensions.geofence_visit_event gv 
INNER JOIN "${access_db}"."${access_schema}"."${access_table}" aoa 
  ON gv.ORGANISATION_ID = aoa.ORGANISATION_ID
 AND LOWER(aoa.REGION) = LOWER('${region}')
 AND UPPER(aoa.CLOUD)  = UPPER('${cloud}');