SELECT 
ID, 
EVENT_ID, 
EVENT_TYPE_ID, 
DETECTION_TAG_ID, 
DRIVER_ID, 
MACHINE_ID, 
MACHINE_ACTIVATION_ID, 
e.ORGANISATION_ID, 
INTENSITY, 
LOCATION_READABLE AS LOCATION, 
LATITUDE, 
LONGITUDE, 
EVENT_START_TIME AS EVENT_DATETIME, 
EVENT_LOCAL_START_TIME AS EVENT_LOCAL_DATETIME, 
EVENT_START_DATE AS EVENT_DATE, 
EVENT_LOCAL_START_DATE AS EVENT_LOCAL_DATE, 
CREATED_AT_BACKEND AS CREATED_DATETIME, 
UPDATED_AT_BACKEND AS UPDATED_DATETIME, 
EVENT_SOURCE, 
VIDEO_DURATION, 
SF_LOAD_DATE AS LOAD_DATETIME 
FROM "${source_db}".core_extensions.media_service_events e 
INNER JOIN "${access_db}"."${access_schema}"."${access_table}" aoa 
  ON e.ORGANISATION_ID = aoa.ORGANISATION_ID
 AND LOWER(aoa.REGION) = LOWER('${region}')
 AND UPPER(aoa.CLOUD)  = UPPER('${cloud}')
 WHERE DISCARDED = FALSE;