SELECT 
ID, 
shdeu.ORGANISATION_ID, 
MACHINE_ID, 
MACHINE_ACTIVATION_ID, 
DRIVER_ID, 
END_DATETIME, 
END_LOCAL_DATETIME, 
END_LOCAL_DATE, 
ODOMETER, 
LATITUDE, 
LONGITUDE, 
START_SPEED, 
END_SPEED, 
LOCATION, 
MAX_ACCELERATION, 
HARSH_DRIVING_TYPE, 
SHARED_MACHINE, 
LOAD_DATE as LOAD_DATETIME 
FROM "${source_db}".core_extensions.shared_harsh_driving_event_union shdeu 
INNER JOIN "${access_db}"."${access_schema}"."${access_table}" aoa 
  ON shdeu.ORGANISATION_ID = aoa.ORGANISATION_ID
 AND LOWER(aoa.REGION) = LOWER('${region}')
 AND UPPER(aoa.CLOUD)  = UPPER('${cloud}');