SELECT 
ID, 
ms.ORGANISATION_ID, 
MACHINE_ID, 
SERVICE_LOCAL_DATE, 
SERVICE_ODOMETER AS ODOMETER, 
AMOUNT, 
SERVICE_TYPE_ID, 
SERVICE_TYPE, 
SERVICE_SUPPLIER, 
CUSTOM_NAME, 
SERVICE_HOURS, 
SERVICE_EBOX_READING, 
INVOICE_NUMBER, 
LOAD_DATE as LOAD_DATETIME 
FROM "${source_db}".core_extensions.machine_service ms 
INNER JOIN "${access_db}"."${access_schema}"."${access_table}" aoa 
  ON ms.ORGANISATION_ID = aoa.ORGANISATION_ID
 AND LOWER(aoa.REGION) = LOWER('${region}')
 AND UPPER(aoa.CLOUD)  = UPPER('${cloud}');