SELECT 
ID, 
di.ORGANISATION_ID, 
MACHINE_ID, 
MACHINE_ACTIVATION_ID, 
DRIVER_ID, 
INSPECTION_DATETIME, 
INSPECTION_LOCAL_DATETIME, 
INSPECTION_LOCAL_DATE, 
DURATION_SECONDS, 
INSPECTION_TYPE, 
INSPECTION_VEHICLE_TYPE, 
SAFE_TO_DRIVE, SOURCE, 
-- INSPECTION_DATA, 
INSPECTION_RESULT, 
DEFECT_IDS, 
SF_LOAD_DATE as LOAD_DATETIME 
FROM "${source_db}".core_extensions.driver_inspection di 
INNER JOIN "${access_db}"."${access_schema}"."${access_table}" aoa 
  ON di.ORGANISATION_ID = aoa.ORGANISATION_ID
 AND LOWER(aoa.REGION) = LOWER('${region}')
 AND UPPER(aoa.CLOUD)  = UPPER('${cloud}');