SELECT 
DISTINCT ID, 
svtu.ORGANISATION_ID, 
MACHINE_ID, 
MACHINE_ACTIVATION_ID, 
DRIVER_ID, 
UUID_STRING(svtu.ORGANISATION_ID, ID || NVL(IFF(TRIP_COUNT = 1, '-1', DRIVER_ID),'-1')) as VEHICLE_TRIP_DRIVER_ID, -- globally unique id 
TRIP_START_DATETIME as START_DATETIME, 
TRIP_START_LOCAL_DATETIME as START_LOCAL_DATETIME, 
TRIP_START_LOCAL_DATE as START_LOCAL_DATE, 
TRIP_END_DATETIME as END_DATETIME, 
TRIP_END_LOCAL_DATETIME as END_LOCAL_DATETIME, 
TRIP_END_LOCAL_DATETIME::DATE as END_LOCAL_DATE, 
TRIP_START_ODOMETER as START_ODOMETER, 
TRIP_END_ODOMETER as END_ODOMETER, 
TRIP_LINESTRING as LINESTRING, 
TRIP_START_LOCATION as START_LOCATION, 
TRIP_END_LOCATION as END_LOCATION, 
SHARED_MACHINE, 
LAST_MODIFIED as LOAD_DATETIME 
FROM "${source_db}".core_extensions.shared_driver_vehicle_trip_union svtu 
INNER JOIN "${access_db}"."${access_schema}"."${access_table}" aoa 
  ON svtu.ORGANISATION_ID = aoa.ORGANISATION_ID
 AND LOWER(aoa.REGION) = LOWER('${region}')
 AND UPPER(aoa.CLOUD)  = UPPER('${cloud}')
 QUALIFY ROW_NUMBER() OVER (PARTITION BY ID, svtu.ORGANISATION_ID, MACHINE_ID, MACHINE_ACTIVATION_ID, DRIVER_ID, TRIP_START_LOCAL_DATE ORDER BY TRIP_COUNT DESC) = 1;