SELECT 
ID, 
sdieu.ORGANISATION_ID, 
MACHINE_ID, 
MACHINE_ACTIVATION_ID, 
SENSOR_NUMBER, 
SENSOR_NAME, 
DISTANCE, 
TIME_SECONDS, 
START_DATETIME, 
START_LOCAL_DATETIME, 
START_LOCAL_DATE, 
END_DATETIME, 
END_LOCAL_DATETIME, 
END_LOCAL_DATE, 
START_ODOMETER, 
END_ODOMETER, 
START_SPEED, 
END_SPEED, 
START_LATITUDE, 
START_LONGITUDE, 
END_LATITUDE, 
END_LONGITUDE, 
START_LOCATION, 
END_LOCATION, 
SHARED_MACHINE, 
LOAD_DATE as LOAD_DATETIME 
FROM "${source_db}".core_extensions.shared_digital_input_event_union sdieu 
INNER JOIN "${access_db}"."${access_schema}"."${access_table}" aoa 
  ON sdieu.ORGANISATION_ID = aoa.ORGANISATION_ID
 AND LOWER(aoa.REGION) = LOWER('${region}')
 AND UPPER(aoa.CLOUD)  = UPPER('${cloud}');