SELECT 
f.ID as ID, 
f.ORGANISATION_ID, 
f.MACHINE_GID as MACHINE_ID, 
f.MACHINE_ACTIVATION_ID, 
f.SENSOR_GID as SENSOR_ID, 
f.FAILURE_MODE_ID, 
CASE f.FAULT_SEVERITY_ID WHEN 'LOW' THEN 1 WHEN 'MEDIUM' THEN 2 WHEN 'HIGH' THEN 3 ELSE 0 END AS FAULT_SEVERITY_ID, 
f.IS_ACTIVE, 
f.FAULT_EVENT_TIMESTAMP as EVENT_DATETIME, 
f.EVENT_DATE, 
f.EVENT_LOCAL_DATETIME, 
f.EVENT_LOCAL_DATE, 
f.OCCURRENCE_COUNT, 
f.AMBER_LAMP_STATUS, 
f.MALFUNCTION_LAMP_STATUS, 
f.PROTECT_LAMP_STATUS, 
f.RED_LAMP_STATUS, 
f.SF_LOAD_DATE as LOAD_DATETIME 
FROM "${source_db}".core_extensions.ecm_faults_generic_sensor_event f 
INNER JOIN "${access_db}"."${access_schema}"."${access_table}" aoa 
  ON f.ORGANISATION_ID = aoa.ORGANISATION_ID
 AND LOWER(aoa.REGION) = LOWER('${region}')
 AND UPPER(aoa.CLOUD)  = UPPER('${cloud}');