SELECT 
ID, 
ft.ORGANISATION_ID, 
MACHINE_ID, 
DRIVER_ID, 
FUEL_TRANSACTION_ID, 
TRANSACTION_DATETIME,
TRANSACTION_LOCAL_DATETIME, 
TRANSACTION_LOCAL_DATE, 
SUPPLIER, 
CUSTOMER_NAME, 
CUSTOMER_ACCOUNT_NUMBER, 
PRODUCT_CODE, 
QUANTITY, 
IFF(ODOMETER >= PREV_ODOMETER, ROUND((ODOMETER - PREV_ODOMETER), 3), DISTANCE) as DISTANCE, 
COST, 
CONSUMER, 
TAX_PAID, 
SOURCE, 
SOURCE_COMPONENT, 
SF_LOAD_DATE as LOAD_DATETIME 
FROM "${source_db}".core_extensions.fuel_transaction ft 
INNER JOIN "${access_db}"."${access_schema}"."${access_table}" aoa 
  ON ft.ORGANISATION_ID = aoa.ORGANISATION_ID
 AND LOWER(aoa.REGION) = LOWER('${region}')
 AND UPPER(aoa.CLOUD)  = UPPER('${cloud}')
WHERE PROCESSING_STATUS != 'REJECTED';