SELECT 
ID, 
dl.ORGANISATION_ID, 
MACHINE_ID, 
DRIVER_ID, 
LOGIN_DATETIME, 
LOGIN_LOCAL_DATETIME, 
LOGIN_LOCAL_DATE, 
LOGOUT_DATETIME, 
LOGOUT_LOCAL_DATETIME, 
LOGOUT_LOCAL_DATE, 
LOGIN_ODOMETER, 
LOGOUT_ODOMETER, 
LOAD_DATE as LOAD_DATETIME 
FROM "${source_db}".core_extensions.driver_log dl
INNER JOIN "${access_db}"."${access_schema}"."${access_table}" aoa 
  ON dl.ORGANISATION_ID = aoa.ORGANISATION_ID
 AND LOWER(aoa.REGION) = LOWER('${region}')
 AND UPPER(aoa.CLOUD)  = UPPER('${cloud}');