
SELECT 
UUID_STRING( ie.ORGANISATION_ID, ie.ORGANISATION_ID || '-' || ie.MACHINE_ID || '-' || to_varchar(ie.START_EVENT_DATETIME, 'YYYY-MM-DDTHH24:MI:SS.FFTZH:TZM') ) as ID, 
ie.ORGANISATION_ID, 
ie.MACHINE_ID, 
null as MACHINE_ACTIVATION_ID, -- //TODO: add to underlying models 
ie.DRIVER_ID, 
ie.ODOMETER, 
null as LOCATION, -- //TODO: add to underlying models 
ie.LATITUDE, 
ie.LONGITUDE, 
ie.START_EVENT_DATETIME, 
ie.START_IDLE_EVENT_LOCAL_DATETIME as START_EVENT_LOCAL_DATETIME, 
ie.START_IDLE_EVENT_LOCAL_DATE as START_EVENT_LOCAL_DATE, 
ie.END_EVENT_DATETIME, 
ie.END_IDLE_EVENT_LOCAL_DATETIME as END_EVENT_LOCAL_DATETIME, 
ie.END_IDLE_EVENT_LOCAL_DATE as END_EVENT_LOCAL_DATE, 
ie.IDLE_SECONDS, 
ie.PTO_SECONDS, 
ie.SF_LOAD_DATE as LOAD_DATETIME 
FROM "${source_db}".core_extensions.idle_event_union ie 
INNER JOIN "${access_db}"."${access_schema}"."${access_table}" aoa 
  ON ie.ORGANISATION_ID = aoa.ORGANISATION_ID
 AND LOWER(aoa.REGION) = LOWER('${region}')
 AND UPPER(aoa.CLOUD)  = UPPER('${cloud}');