SELECT 
STATUS_CHANGE_ID as ID, 
te.ORGANISATION_ID, 
DRIVER_ID, 
VALID_TIME_UTC as EVENT_DATETIME, 
EVENT_LOCAL_DATETIME, 
EVENT_LOCAL_DATE, 
STATUS_STRING as STATUS, 
LATITUDE, 
LONGITUDE, 
SUBURB_FROM_GPS, 
SUBURB_ENTERED, 
CREATED_DATETIME, 
LASTMODIFIED_DATETIME, 
REGISTRATION, 
VEHICLE_TYPE_STRING as VEHICLE_TYPE, 
ODOMETER, 
NOTES, 
EDIT_INDEX AS EDITS, 
LOAD_DATETIME 
FROM "${source_db}".core_extensions.timely_event_historic_union te 
INNER JOIN "${access_db}"."${access_schema}"."${access_table}" aoa 
  ON te.ORGANISATION_ID = aoa.ORGANISATION_ID
 AND LOWER(aoa.REGION) = LOWER('${region}')
 AND UPPER(aoa.CLOUD)  = UPPER('${cloud}');