SELECT 
ID, 
emei.ORGANISATION_ID, 
MACHINE_ID, 
MACHINE_ACTIVATION_ID, 
EVENT_DATETIME, 
EVENT_LOCAL_DATETIME, 
EVENT_LOCAL_DATE, 
ODOMETER, 
LATITUDE, 
LONGITUDE, 
LOCATION, 
SPEED, 
emei.EVENT_TYPE_NAME as EVENT_TYPE, 
ADDITIONAL_DATA, 
SHARED_MACHINE, 
SF_LOAD_DATE as LOAD_DATETIME 
FROM "${source_db}".core_extensions.shared_ebox_machine_event_union emei 
INNER JOIN "${access_db}"."${access_schema}"."${access_table}" aoa 
  ON emei.ORGANISATION_ID = aoa.ORGANISATION_ID
 AND LOWER(aoa.REGION) = LOWER('${region}')
 AND UPPER(aoa.CLOUD)  = UPPER('${cloud}');