SELECT 
ID, 
sdmru.ORGANISATION_ID, 
MACHINE_ID, 
MACHINE_ACTIVATION_ID, 
START_LOCAL_DATE, 
TIMEZONE, 
DISTANCE, 
OFFROAD_DISTANCE, 
DEGRADED_DISTANCE, 
RUNNING_TIME_SECONDS, 
STOP_TIME_SECONDS, 
IDLE_TIME_SECONDS, 
IDLE_OFFROAD_TIME_SECONDS, 
LOW_IDLE_EVENT_COUNT, 
MEDIUM_IDLE_EVENT_COUNT, 
HIGH_IDLE_EVENT_COUNT, 
SITE_VISIT_COUNT, 
LOW_OVERSPEED_COUNT, 
MEDIUM_OVERSPEED_COUNT, 
HIGH_OVERSPEED_COUNT, 
VIRTUAL_SPEED_COUNT, 
SENSOR1_TOTAL_TIME, 
SENSOR1_TOTAL_DISTANCE, 
SENSOR2_TOTAL_TIME, 
SENSOR2_TOTAL_DISTANCE, 
SENSOR3_TOTAL_TIME, 
SENSOR3_TOTAL_DISTANCE, 
DEPOT_TOTAL_TIME, 
SHARED_MACHINE, 
LOAD_DATE as LOAD_DATETIME 
FROM "${source_db}".core_extensions.shared_daily_machine_report_union sdmru 
INNER JOIN "${access_db}"."${access_schema}"."${access_table}" aoa 
  ON sdmru.ORGANISATION_ID = aoa.ORGANISATION_ID
 AND LOWER(aoa.REGION) = LOWER('${region}')
 AND UPPER(aoa.CLOUD)  = UPPER('${cloud}');