SELECT 
ID, 
sosu.ORGANISATION_ID, 
MACHINE_ID, 
MACHINE_ACTIVATION_ID, 
DRIVER_ID, 
START_DATETIME, 
START_LOCAL_DATETIME, 
START_LOCAL_DATE, 
END_DATETIME, 
END_LOCAL_DATETIME, 
END_LOCAL_DATE, 
START_ODOMETER, 
END_ODOMETER, 
START_LATITUDE, 
START_LONGITUDE, 
END_LATITUDE, 
END_LONGITUDE, 
START_SPEED, 
END_SPEED, 
SPEED_LIMIT as START_SPEED_LIMIT, 
SPEED_LIMIT as END_SPEED_LIMIT, 
START_LOCATION, 
END_LOCATION, 
MAX_SPEED, 
MAX_SPEED_BAND, 
SPEED_LIMIT as MIN_SPEED_LIMIT, 
SHARED_MACHINE, 
LOAD_DATETIME 
FROM "${source_db}".core_extensions.shared_overspeed_sessions_zoned_union sosu
INNER JOIN "${access_db}"."${access_schema}"."${access_table}" aoa 
  ON sosu.ORGANISATION_ID = aoa.ORGANISATION_ID
 AND LOWER(aoa.REGION) = LOWER('${region}')
 AND UPPER(aoa.CLOUD)  = UPPER('${cloud}');