select 
ID, 
vl.ORGANISATION_ID, 
MACHINE_ID, 
EFFECTIVE_DATE_LOCALISED as EFFECTIVE_LOCAL_DATE, 
CURRENT_STARS, 
rank() over (partition by NVL(CENTRAL_VIEWING_ORGANISATION_ID,CENTRAL_ORGANISATION_ID),
EFFECTIVE_DATE_LOCALISED ORDER BY CURRENT_SCORE DESC, DISTANCE DESC) as ORGANISATION_RANK, 
SHARED_MACHINE 
FROM "${source_db}".core_extensions.vehicle_leaderboard vl 
INNER JOIN "${access_db}"."${access_schema}"."${access_table}" aoa 
  ON vl.ORGANISATION_ID = aoa.ORGANISATION_ID
 AND LOWER(aoa.REGION) = LOWER('${region}')
 AND UPPER(aoa.CLOUD)  = UPPER('${cloud}');