SELECT 
ID, 
DEFECT_ID, 
MACHINE_ID, 
dl.ORGANISATION_ID, 
INSPECTION_CATEGORY_NAME, 
ITEM_NAME, 
INSPECTION_ITEM_RESULT, 
SAFE_TO_DRIVE, 
DESCRIPTION, 
STATUS, 
STATUS_INITIATED_DATETIME, 
STATUS_INITIATED_LOCAL_DATETIME, 
STATUS_INITIATED_LOCAL_DATE, 
IS_SERVICE_REPAIR, 
SF_LOAD_DATE as LOAD_DATETIME 
FROM "${source_db}".core_extensions.defect_log dl 
INNER JOIN "${access_db}"."${access_schema}"."${access_table}" aoa 
  ON dl.ORGANISATION_ID = aoa.ORGANISATION_ID
 AND LOWER(aoa.REGION) = LOWER('${region}')
 AND UPPER(aoa.CLOUD)  = UPPER('${cloud}');